accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import (
    signup,
)


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include("receipts.urls")),
    path('accounts/', include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path


from receipts.views import (
    AccountListView,
    AccountCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    ReceiptCreateView,
    ReceiptListView,
)



urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_expensecategory"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="create_expensecategory"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

accounts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


# Create your views here.

# Function View
    # If request is a form
        # Create form
        # If the form is valid, save user
        # Login the user w/ login() function
        # Redirect to "home"
    # Otherwise request is not POST
        # Go to user creation instead
    # return render()
    
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
        
    return render(request, 'registration/signup.html', {'form': form})

receipts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.urls import reverse_lazy
from receipts.models import ExpenseCategory, Account, Receipt

USER_MODEL = settings.AUTH_USER_MODEL


# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/receipt_list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/receipt_create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"
    
    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/expense_create.html"
    fields = ["name"]

    def form_valid(self, form):
        expensecategory = form.save(commit=False)
        expensecategory.owner = self.request.user
        expensecategory.save()
        return redirect("list_expensecategory")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect("list_accounts")

receipts/templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'home' %}">Receipts</a>
                </li>
                <li>
                    <a href="{% url 'create_receipt' %}">Create a Receipt</a>
                </li>
                <li>
                    <a href="{% url 'list_accounts' %}">Accounts</a>
                </li>
                <li>
                    <a href="{% url 'create_account' %}">Create an Account</a>
                </li>
                <li>
                    <a href="{% url 'list_expensecategory' %}">Expense Categories</a>
                </li>
                <li>
                    <a href="{% url 'create_expensecategory' %}">Create an Expense Category</a>
                </li>
                <li>
                  <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                  <a href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'signup' %}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <header>
            {% block header %}
            {% endblock header %}
        </header>
        <main>
            {% block main %}
            {% endblock main %}
        </main>
        <footer>
            {% block footer %}
            {% endblock footer %}
        </footer>
    </body>
</html>

receipts/templates/blank.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
{% endblock main %}

{% block footer %}
{% endblock footer %}

receipts/templates/receipts/account_create.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
<div>
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</div>
{% endblock main %}

{% block footer %}
{% endblock footer %}

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
<h1>My Accounts</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td>{{ account.name }}</td>
            <td>{{ account.number }}</td>
            <td>{{ account.receipts|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock main %}

{% block footer %}
{% endblock footer %}

receipts/templates/receipts/expense_create.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
<div>
    <h1>Create Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</div>
{% endblock main %}

{% block footer %}
{% endblock footer %}

receipts/templates/receipts/expense_list.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
<h1>My Expenses</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for expense in expensecategory_list %}
        <tr>
            <td>{{ expense.name }}</td>
            <td>{{ expense.receipts|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock main %}

{% block footer %}
{% endblock footer %}

receipts/templates/receipts/receipt_create.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
<div>
    <h1>Create Receipt</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</div>
{% endblock main %}

{% block footer %}
{% endblock footer %}

receipts/templates/receipts/receipt_list.html
{% extends 'base.html' %}

{% block title %}
Receipts
{% endblock title %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
<h1>My Receipts</h1>
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Due Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date }}</td>
            <td>{{ receipt.category }}</td>
            <td>{{ receipt.account }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock main %}

{% block footer %}
{% endblock footer %}